version: "3.9"

networks:
  blogapp-network:

services:
  blogapp-sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "2@LaiNw)PDvs^t>L!Ybt]6H^%h3U>M"
      ACCEPT_EULA: "Y"
    networks:
      - blogapp-network
