global using football.history.api.Repositories;
global using football.history.api.Tests.TestUtilities;
global using football.history.api.Domain;
global using football.history.api.Models;
global using football.history.api.Builders;
global using football.history.api.Exceptions;

global using FluentAssertions;
global using Microsoft.AspNetCore.Mvc.Testing;
global using Microsoft.Data.SqlClient;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.SqlServer.Management.Common;
global using Microsoft.SqlServer.Management.Smo;
global using Moq;
global using Newtonsoft.Json;
global using NUnit.Framework;
global using System.Collections;
global using System.Data.Common;
global using System.Net;
