# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  buildConfiguration: 'Release'

steps:
- script: |
    dotnet build FootballHistory.Api --configuration $(buildConfiguration)
    dotnet build FootballHistory.Api.UnitTests --configuration $(buildConfiguration)
    dotnet publish FootballHistory.Api --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY
    dotnet publish FootballHistory.Api.UnitTests --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY
  displayName: 'dotnet build $(buildConfiguration)'

- task: PublishBuildArtifacts@1
