# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'vs2017-win2016'
  
variables:
  buildConfiguration: 'Release'

steps:
- script: |
    dotnet build FootballHistory.Api --configuration $(buildConfiguration)
    dotnet publish FootballHistory.Api --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY
  displayName: 'dotnet build $(buildConfiguration)'

- task: PublishBuildArtifacts@1
