name: Deploy API

on: 
  push: [ main ]

env:
  AZURE_WEBAPP_NAME: football-history-api   
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}