name: Build and Test API

on: [ push ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-restore --no-build --verbosity normal --logger trx --results-directory "APITestResults"

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: api-test-results
        path: APITestResults
      if: ${{ always() }}

    - name: Publish
      run: dotnet publish --configuration Release --no-restore

    - name: Upload FootballHistoryAPI Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: FootballHistoryAPI
        path: ${{ env.GITHUB_WORKSPACE }}/football-history/football-history/football-history-api/bin/Release/net5.0/publish/